### ISSUE TITLE
feature - rgb-ansi format

### ISSUE THREAD

**Issue by const-void** [rose-pine/build#7]
Hello!  What a cool tool! Very nicely done, and so well documented!  Thank you for taking the time to 'do it right'.  

When we have a spare moment...

## Q1 Feature: `-f rgb-ansi` - ok?
I was wondering if it would be ok if I  submit a PR to add a `rgb-ansi` format, that given `235, 188, 186` results in `235;188;186`?

This way,  `@rose-pine/build`  could be used to create imports suitable for rendering rose-pine colors in truecolor terminal scripts.    

### Q2 - force space removal?
If we're good with the feature, for awareness, ANSI truecolor terminal tokens are very unfriendly to spaces--terminals will reject the token as invalid and not apply the color command.  It might be good to force space removal to prevent "accidents" --  I can't imagine there is a usecase for `r; g; b` over `r;g;b`.

If that makes sense, there are two ways to potentially approach, and I was wondering what our preference would be?

**opt a** - remove spaces inside  `rgb-ansi` via `formattedRgb.replaceAll(", ", ";")`   -- efficient
**opt b** - when format is `rgb-ansi`, set `stripSpaces` to true -- lexical
**opt c** -  don't...defer to config -- fewer changes, but  I suspect it might be a gotcha later (something one has to remember)?

### Q3 - where to place?
I was thinking of placing quasi-alphabetically (src, doc, tst)...ansi < array?
```
rgb
rgb-ns
rgb-ansi #<-- ok?
rgb-array
rgb-function
```

thank you again!

**Comment by mvllow** [comment]
Hi there, thank you for the detailed post! I fully support adding an `rgb-ansi` format. As far as removing spaces, I appreciate the multiple options you listed. Personally it shouldn't matter since the output would not include spaces, and adding `--strip-spaces` would technically still remove them, even though none would exist. On the contrast, if `--strip-spaces=false` is added then no spaces should be added because none would exist normally. So I guess this is saying to ignore this option from a mental standpoint but code-wise this new format should operate the same as others. Hope that makes sense!

Edit: to address Q3, your preference is fine with me :)
